twig:
    default_path: '%kernel.project_dir%/templates'
     # activation des thèmes de formulaires Bootstrap pour Symfony
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
