
/** AJOUT DE TOUTES LES BRASSERIES*/
INSERT INTO `brewerie` (`name`, `address`, `zipcode`, `city`, `state`, `website`) VALUES
('La Vardaf (Brasserie raisonnée)', '245 Chem. des Crettets', 74470, 'Bellevaux', 'Auvergne-Rhône-Alpes', 'https://lavardaf.fr/bieres-bio-locales-haut-chablais/' ),
("Bière bio des Monts d'Or", "18 Chemin des Carrières", 69250, "Curis-au-Mont-d'Or", 'Auvergne-Rhône-Alpes', 'https://www.bieresbio.fr/' ),
('Brasserie Volcane', 'ZA de Largelier, 7 Rue de la Côte', 43100, 'Cohade', 'Auvergne-Rhône-Alpes', 'http://www.biere-volcane.fr/' ),
('Brasserie de Vezelay', 'rue du Gravier', 43100, 'Cohade', 'Bourgogne-Franche-Comté', 'https://brasseriedevezelay.fr/' ),
('Maddam (Brasserie de Chablis)', '4 rue des Vendanges', 89800, 'Chablis', 'Bourgogne-Franche-Comté', 'https://www.maddam-chablis.com/' ),
('Brasserie la bonne bouille', '14 Rue du Magasin', 25300, 'Pontarlier', 'Bourgogne-Franche-Comté', 'https://www.brasseriebonnebouille.com/' ),
('Merlin Hops Brewing more', '40 impasse Ru Land', 29760, 'Penmarch', 'Bretagne', 'https://www.merlin.beer/' ),
('Brasserie des Abers', '2 avenue de Portsall', 29830, 'Ploudalmézeau', 'Bretagne', 'https://www.facebook.com/brasseriedesabers/' ),
("L'Amer d'Iroise", '2 impasse du Steir', 29770, 'Plogoff', 'Bretagne', 'https://amer-iroise.beer/' ),
('Art & Brew', '3 Rue Durfort de Duras', 41600, 'Lamotte-Beuvron', 'Centre-Val-de-Loire', 'https://artandbrew.fr/' ),
('Brasserie Ouche Nanon', '2 Place du Marché', 18350, 'Ourouer-les-Bourdelins', 'Centre-Val-de-Loire', 'https://www.ouche-nanon.fr/' ),
('Micro Brasserie Nogentaise', '24 Rue Sainte-Anne', 28400, 'Nogent-le-Rotrou', 'Centre-Val-de-Loire', 'https://brasserie-nogentaise.pagesperso-orange.fr/' ),
('Brasserie Galibot', '5 Rue Jules Verne ', 57600, 'Forbach', 'Grand-Est', 'https://www.brasserie-galibot.com/accueil' ),
('Reims Royal Beer', '15 Cours Anatole France', 51100, 'Reims', 'Grand-Est', 'https://www.reimsroyalbeer.fr/' ),
('Ardwen', '20 Av. Roger Ponsart', 08430, 'Launois-sur-Vence', 'Grand-Est', 'https://www.ardwen.fr/' ),
('Brasserie Quentovic', '27, rue du collège', 62990, 'Beaurainville ', 'Hauts-de-France', 'http://quentovic.com/' ),
('Brasserie de la Somme', '7 route de Berneuil', 80620, 'Domart-en-Ponthieu', 'Hauts-de-France', 'https://www.brasseriedelasomme.fr/' ),
("Brasserie de l'Escaut", "1 Place Charles de Gaulle", 02420, 'Vendhuile', 'Hauts-de-France', 'https://www.facebook.com/labrasseriedelescaut/?locale=fr_FR'),
("Les 3 Brasseurs", "9 rue des Erables - Le Clos de Santeuil", 95610, 'Eragny', 'Ile-de-France', 'https://www.3brasseurs.com' ),
('Brasserie de Meaux', "11 Rue des Buttes Blanches", 77100, 'Meaux', 'Ile-de-France', 'https://www.brasseriedemeaux.com' ),
('Brasserie Hespebay', '29 Rue Carnot', 95410, 'Groslay', 'Ile-de-France', 'https://www.hespeday.fr' ),
('Brasserie La Lie ', "400 Rue de l'Orne", 14570, 'Saint Remy', 'Normandie', 'https://www.biere-lalie.com' ),
('Brasserie les Deux Ammants', "1 voie des Vendaises", 27100, 'Val-de-Reuil', 'Normandie', 'https://www.lesdeuxamants.com' ),
("Brasserie de l'Odon", '31 bis Rue de Vire', 14260, "Les Monts d'Aunay", 'Normandie', 'https://www.brasserie-odon.fr' ),
('Azimut Brasserie', '5 Av. du Dr Schinazi', 33000, 'Bordeaux', 'Nouvelle-Aquitaine', 'https://www.azimutbrasserie.com' ),
('Biere de la Bastide', '12 Rue du Balaitous', 64000, 'Pau', 'Nouvelle-Aquitaine', 'https://www.brasserie-bearnaise.fr' ),
('Brasserie La Lutine', 'Route du Bugue', 24510, 'Limeul', 'Nouvelle-Aquitaine', 'https://www.lalutine.com' ),
('La Commingeoise', '225 route de la Grangette', 31360, 'Sepx', 'Occitanie', 'https://www.facebook.com/la.commingeoise/' ),
('La Brasserie du Lez', '7b za Sainte Julie', 34980, 'Montferrier-sur-Lez', 'Occitanie', 'https://www.brasserie-du-lez.beer' ),
('La Brasserie du Pépère', '5 Avenue de la Gare', 32100, 'Condom', 'Occitanie', 'https://www.labrasseriedupepere.fr' ),
('Brasserie Nao', '2 rue Albert De Dion', 44360, 'Vigneux-de-Bretagne', 'Pays-de-la-Loire', 'https://bieres-nao.fr' ),
('Les Bières de Charlotte', '121, rue du Général Buat', 44000, 'Nantes', 'Pays-de-la-Loire', 'https://www.lesbieresdecharlotte.fr' ),
('Brasserie des Chats Noirs', 'ZA La Grolle', 85150, 'Landeronde', 'Pays-de-la-Loire', 'https://www.facebook.com/brasseriedeschatsnoirs/' ),
('Brasserie Artisanale La Maure', '1065 Chemin de Bénat', 83230, 'Bormes-les-Mimosas', "Provence-Alpes-Côte d'Azur", 'https://www.facebook.com/bap.lamaure/' ),
('Brasserie La Dejantee', '53 Rue Porte Notre Dame', 84210, 'Pernes-les-Fontaines', "Provence-Alpes-Côte d'Azur", 'https://www.facebook.com/brasserieladejantee' ),
('Arlatina', '70 Draille du Mas Mollin', 13200, 'Arles', "Provence-Alpes-Côte-d'Azur", 'https://www.facebook.com/profile.php?id=100027305241177' ),
('Bière artisanale TY CORSA', 'Domaine Isula Tonda', 20243, 'Prunelli-di-Fiumorbo', 'Corse', '' ),
("Micro brasserie impériale", "5 Rue Zevaco Maire", 20000, "Ajaccio", 'Corse', '' ),
('Brasserie Ribella', 'Route de Saint-Florent', 20253, 'Patrimonio', 'Corse', 'https://biereribella.com/')